// Download the Open Sans woff2 files we use (latin + latin-ext, weights
// 400-800) from Google Fonts and emit a local @font-face stylesheet, so the
// site self-hosts the font instead of fetching it from fonts.googleapis.com.
// Run: node scripts/fetch-fonts.js
const fs = require("fs");
const path = require("path");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700;800&display=swap";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const KEEP = new Set(["latin", "latin-ext"]);

const FONT_DIR = path.join(__dirname, "..", "assets", "fonts");
const CSS_OUT = path.join(__dirname, "..", "assets", "css", "fonts.css");

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });

  const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

  const blockRe =
    /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  const out = [
    "/* =======================================================================",
    "   Open Sans — self-hosted (SIL OFL). Generated by scripts/fetch-fonts.js.",
    "   Subsets: latin, latin-ext (Czech). Weights: 400,500,600,700,800.",
    "   ======================================================================= */",
    "",
  ];
  let count = 0;

  for (const m of css.matchAll(blockRe)) {
    const subset = m[1];
    const body = m[2];
    if (!KEEP.has(subset)) continue;

    const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (body.match(/url\((https:\/\/[^)]+)\)/) || [])[1];
    const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!weight || !url) continue;

    const file = `open-sans-${subset}-${weight}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    fs.writeFileSync(path.join(FONT_DIR, file), buf);
    count++;

    out.push(
      "@font-face {",
      "  font-family: 'Open Sans';",
      "  font-style: normal;",
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      `  src: url(../fonts/${file}) format('woff2');`,
      `  unicode-range: ${range};`,
      "}",
      ""
    );
    console.log("downloaded", file, buf.length + " bytes");
  }

  fs.writeFileSync(CSS_OUT, out.join("\n"));
  console.log(`\nwrote ${CSS_OUT} (${count} faces)`);
}
main().catch((e) => { console.error(e); process.exit(1); });
